### ISSUE TITLE
example LightAndBillboard not working in zoomed chrome

### ISSUE THREAD

**Issue by splace** [kitao/divsugar#16]
when viewed in chrome, 28, in anything but unzoomed, boxes are in two halves. 

![screenshot from 2013-09-05 23 18 18](https://f.cloud.github.com/assets/1234848/1092283/59e6a348-1679-11e3-8b45-6262a5bb62bb.png)

**Comment by kitao** [comment]
It seems that it works fine in the latest version of Chrome.

**Comment by dgu123** [comment]
amazing work
